--Inserts for courses
INSERT INTO TB_COURSE (name) VALUES ('TDD');
INSERT INTO TB_COURSE (name) VALUES ('JavaScript');
INSERT INTO TB_COURSE (name) VALUES ('Java');
INSERT INTO TB_COURSE (name) VALUES ('Banco De Dados');
INSERT INTO TB_COURSE (name) VALUES ('HTML');
INSERT INTO TB_COURSE (name) VALUES ('CSS');
INSERT INTO TB_COURSE (name) VALUES ('Clean Code');
INSERT INTO TB_COURSE (name) VALUES ('SOLID');